apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: grafana
  labels:
    app: loki
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.5.7
          args:
            - "--config.file=/mnt/config/loki-config.yaml"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-config
              mountPath: /mnt/config
              readOnly: true
      volumes:
        - name: loki-config
          nfs:
            server: 10.60.1.15
            path: /data/services/loki/config
